/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar in the docs site
 - List of categorization categories and their link
 - Guide the user through your documentation in a clear order
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapters',
      items: [
        'foundations',
        'ros',
        'simulation',
        'isaac',
        'vla',
        'kinematics',
        'manipulation',
        'gpt',
        'learning',
        'ethics',
        'locomotion',
        'capstone',
      ],
    },
  ],
};

module.exports = sidebars;